/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import {HttpClient, HttpContext, HttpResponse} from '@angular/common/http';
import {Observable} from 'rxjs';
import {filter, map} from 'rxjs/operators';
import {StrictHttpResponse} from '../../strict-http-response';
import {RequestBuilder} from '../../request-builder';

import {AuthRequest} from '../../models/auth-request';
import {AuthResponse} from '../../models/auth-response';

export interface VerifyUser$Params {
    body: AuthRequest
}

export function verifyUser(http: HttpClient, rootUrl: string, params: VerifyUser$Params, context?: HttpContext): Observable<StrictHttpResponse<AuthResponse>> {
    const rb = new RequestBuilder(rootUrl, verifyUser.PATH, 'post');
    if (params) {
        rb.body(params.body, 'application/json');
    }

    return http.request(
        rb.build({responseType: 'json', accept: 'application/json', context})
    ).pipe(
        filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
        map((r: HttpResponse<any>) => {
            return r as StrictHttpResponse<AuthResponse>;
        })
    );
}

verifyUser.PATH = '/auth/verify';
