/* tslint:disable */
/* eslint-disable */

/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface RegisterRequest {
    dateOfBirth?: string;
    firstname: string;
    lastname: string;
    password?: string;
    userEmail?: string;
}
